import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Manrope, Plus_Jakarta_Sans } from "next/font/google";
import Sidebar from "../components/Sidebar/Sidebar";

// 1. Manrope შრიფტის კონფიგურაცია
const manrope = Manrope({
  subsets: ['latin'],
  variable: '--font-main',
});

// 2. Plus Jakarta Sans შრიფტის კონფიგურაცია
const jakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  variable: '--font-secondary',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${manrope.variable} ${jakarta.variable}`}
    >
      <body className="min-h-full flex flex-col">
        <Sidebar />
        <div className="flex-1 flex flex-col min-h-screen">
          {/* <Header /> */}
          <main className="flex-1 p-6">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
