import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Manrope, Plus_Jakarta_Sans } from "next/font/google";
import Sidebar from "../components/layout/Sidebar/Sidebar";
import Header from "../components/layout/Header/Header";

// 1. Manrope შრიფტის კონფიგურაცია
const manrope = Manrope({
  subsets: ['latin'],
  variable: '--font-main',
});

// 2. Plus Jakarta Sans შრიფტის კონფიგურაცია
const jakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  variable: '--font-secondary',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${manrope.variable} ${jakarta.variable}`} suppressHydrationWarning>
      <body>

        <div className="layout-wrapper">
          <Sidebar />

          <div className="main-wrapper">
            <Header />
            <main className="content">
              {children}
            </main>
          </div>
        </div>

      </body>
    </html>
  );
}
